### PR TITLE
Pushed root-level docs

### PR DESCRIPTION
**Pull request by skc222**
Resolves issue https://github.com/pyne/pyne.github.com/issues/6
Link to rebuilt website from fork: https://skc222.github.io/pyne.github.com/

### CODE REVIEW

**Comment by katyhuff** [comment]
Thanks for this! Quick question before I merge: did anything need to change in the source branch for this to work, or was it just an environment issue during build?

**Review by katyhuff — APPROVED** [review]
this looks good to me.

**Comment by skc222** [comment]
No just an environment issue during build. I didn't make any changes in source branch.

**Comment by katyhuff** [comment]
bitmoji

**Pull request merged**
